"""Phase-2 risk-concentration measures (variance-share), operating on a
weight vector restricted to a point-in-time top-N subset and its estimated
covariance matrix Sigma_t (src/concentration/covariance_estimation.py) -
distinct from src/concentration/measures.py, whose functions take only a
weight vector (a single date's capital-weight distribution). Risk
concentration is defined on the Euler decomposition of portfolio variance,
so it needs the (weights, Sigma_t) pair, not weights alone.

Concept boundary: none of these functions touch the correlation matrix or
its eigenvalues - that is dependence concentration's territory (a separate,
not-yet-built CSI dimension), kept deliberately out of scope here even
though it would reuse the same Sigma_t estimation module.
"""

from __future__ import annotations

import numpy as np


def risk_contributions(weights: np.ndarray, sigma: np.ndarray) -> np.ndarray:
    """Euler risk contributions p_i,t = w_i * (Sigma w)_i / (w' Sigma w).

    Sums to exactly 1 by Euler's theorem (w' Sigma w is homogeneous degree
    2 in w), regardless of whether `weights` itself sums to 1 - so
    `weights` should be each name's ACTUAL point-in-time market weight
    within the estimation subset (not renormalized to sum to 1 over the
    subset), matching the "risk shares" definition in
    docs/methodology_notes/csi_construction.md.

    Individual p_i,t CAN be negative (a name whose covariance with the
    subset portfolio is negative despite a positive weight) - a known
    feature of Euler risk decomposition, not a bug. See risk_entropy below
    for how this project handles it.
    """
    w = np.asarray(weights, dtype=float)
    portfolio_var = float(w @ sigma @ w)
    if portfolio_var <= 0:
        raise ValueError("portfolio variance must be positive")
    marginal = sigma @ w
    return (w * marginal) / portfolio_var


def risk_share_topk(weights: np.ndarray, sigma: np.ndarray, topk_mask: np.ndarray) -> float:
    """Fraction of total (subset) portfolio variance generated by the
    top-k-BY-WEIGHT cohort (`topk_mask`, a boolean array aligned with
    `weights`/`sigma`'s ordering) - not top-k by risk contribution itself.

    Ranking by weight (the same cohort CR-k uses) rather than by risk
    contribution is deliberate: ranking by risk contribution would make
    "this cohort's share of risk" tautologically close to 100% by
    construction (you'd be selecting the highest risk contributors, then
    asking how much risk they contribute), whereas ranking by weight
    answers the non-tautological question "does the cohort that holds X%
    of the CAPITAL also generate X% of the RISK, more, or less?".
    """
    p = risk_contributions(weights, sigma)
    return float(p[topk_mask].sum())


def effective_n_risk(weights: np.ndarray, sigma: np.ndarray) -> float:
    """N_eff_risk = 1 / sum(p_i,t^2) - risk-space analogue of effective_n,
    computed over the FULL estimation subset (not just the top-k cohort).

    Directionality warning, same as effective_n in measures.py: HIGHER
    N_eff_risk means LESS risk concentration - see
    RISK_CONCENTRATION_DIRECTION below.
    """
    p = risk_contributions(weights, sigma)
    return float(1.0 / np.sum(p**2))


def risk_entropy(weights: np.ndarray, sigma: np.ndarray) -> float:
    """1 - normalized Shannon entropy of the risk shares p_i,t, over the
    full estimation subset - direction-matched to entropy_concentration in
    measures.py (higher = more concentrated).

    Not part of docs/methodology_notes/csi_construction.md's original
    risk-concentration spec (which only proposed risk_share_topk and
    N_eff_risk) - added by analogy to the Phase-2 capital-concentration
    result, where entropy_concentration turned out to be the one measure
    carrying short-run information the CR-k family didn't. Whether the
    same holds in risk-space is an empirical question for the
    risk-concentration collinearity check, not assumed here.

    Shannon entropy requires non-negative shares, but p_i,t can be
    negative (see risk_contributions). Convention adopted: negative
    p_i,t are CLIPPED to 0 before the entropy calculation - a name with a
    negative risk contribution is, for "how concentrated is the
    portfolio's risk-generating capacity", contributing none of it, not a
    negative amount of it. The clipped shares are NOT renormalized to sum
    back to 1 (so this differs from a textbook entropy of a probability
    distribution when clipping actually changes anything); the
    denominator stays ln(n) - the subset size's max-entropy benchmark -
    for direct comparability with entropy_concentration's own convention
    of normalizing by ln(n) rather than by the realized share total. See
    docs/variable_definitions/risk_concentration.md for the empirical
    frequency of negative p_i,t found in this project's sample.
    """
    p = risk_contributions(weights, sigma)
    n = p.size
    if n <= 1:
        return 1.0
    clipped = np.clip(p, 0.0, None)
    nonzero = clipped[clipped > 0]
    if nonzero.size == 0:
        return 0.0
    h = float(-np.sum(nonzero * np.log(nonzero)))
    h_max = np.log(n)
    return float(1.0 - h / h_max)


# +1: higher value = more risk-concentrated (aggregation-ready sign as-is).
# -1: higher value = LESS risk-concentrated (must be sign-flipped before
# combining with +1 measures in any future z-score/PCA aggregation, exactly
# the effective_n / CONCENTRATION_DIRECTION pattern in measures.py).
RISK_CONCENTRATION_DIRECTION = {
    "risk_share_top5": 1,
    "risk_share_top7": 1,
    "risk_share_top10": 1,
    "n_eff_risk": -1,
    "risk_entropy": 1,
}


def risk_concentration_direction(measure_name: str) -> int:
    """Aggregation sign for a risk-concentration measure name."""
    if measure_name in RISK_CONCENTRATION_DIRECTION:
        return RISK_CONCENTRATION_DIRECTION[measure_name]
    if measure_name.startswith("risk_share_top"):
        return 1
    raise KeyError(f"no known risk-concentration-direction sign for '{measure_name}'")
